/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Item } from "./components/items-card/item";
export { Item } from "./components/items-card/item";
export namespace Components {
    interface EyItemsCard {
        "arrayData": Item[] | string;
    }
}
declare global {
    interface HTMLEyItemsCardElement extends Components.EyItemsCard, HTMLStencilElement {
    }
    var HTMLEyItemsCardElement: {
        prototype: HTMLEyItemsCardElement;
        new (): HTMLEyItemsCardElement;
    };
    interface HTMLElementTagNameMap {
        "ey-items-card": HTMLEyItemsCardElement;
    }
}
declare namespace LocalJSX {
    interface EyItemsCard {
        "arrayData"?: Item[] | string;
    }
    interface IntrinsicElements {
        "ey-items-card": EyItemsCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ey-items-card": LocalJSX.EyItemsCard & JSXBase.HTMLAttributes<HTMLEyItemsCardElement>;
        }
    }
}
